### ISSUE TITLE
Extension does not work for some searches

### ISSUE THREAD

**Issue by PaoloCortezCZ** [mrakowski0/readd-gmaps-links-chrome-extension#1]
I have noticed that when I search some specific cities such as Dallas or Atlanta, your extension does not work.

![SCR-20240330-dql](https://github.com/mrakowski0/readd-gmaps-links-chrome-extension/assets/163757672/3d7f054b-ffbc-4328-95fe-e781100aa087)

**Comment by mrakowski0** [comment]
Hi @PaoloCortezCZ thank you for creating this issue, I have indentified a few occurences where the UI elements are not properly selected (google has a ton of variants of map UI and they also run A/B testing that make the html markup a little bit unpredictible at times). 

I will try to fix it in the next couple of days and release a new version 👍

**Comment by mrakowski0** [comment]
Fixed in ce4323df3528fcb2d09fc6a308c9899a84cf2171
