### ISSUE TITLE
[Bug] Wrong button in mobile view

### ISSUE THREAD

**Issue by adripo** [mrakowski0/readd-gmaps-links-chrome-extension#2]
Maps button has wrong style when mobile view is active.

Steps to reproduce:
1. New tab
2. Open Developer Tools (F12)
3. Enable device toolbar and choose any phone (e.g. iPhone)
4. Search a place in browser searchbar

![2024-04-13_02-55-12-659_brave](https://github.com/mrakowski0/readd-gmaps-links-chrome-extension/assets/26493496/e1091339-82e0-42a4-bbc8-24eb6435b2a7)

**Comment by mrakowski0** [comment]
Thanks for creating an issue, I'm aware of some mobile issues. It's a very minor % of the current user base but I'll try to fix it anyways 👍

**Comment by mrakowski0** [comment]
Closig this as currently chrome mobile does not support extensions so mobile web is not really a concern at this point.
Fixing this would be having to maintain support for yet another variant for not a big return (if any).

I will try to rotate back to this if i have the time to find a more reliable solution, feel free to open a PR if you think it can be done in a more reliable way than deriving classes from the markup.

**Comment by adripo** [comment]
Okay, you are right, chrome mobile does not support extensions
