### ISSUE TITLE
[Improvement] `OPEN IN MAPS` overlay 

### ISSUE THREAD

**Issue by adripo** [mrakowski0/readd-gmaps-links-chrome-extension#3]
I would suggest to improve the overlay by:

- Changing the text style to make it more harmonic with the page style
- Keeping same button size when opening in-page maps container because now it stays over maps zoom buttons

![2024-04-13_02-48-28-314_brave](https://github.com/mrakowski0/readd-gmaps-links-chrome-extension/assets/26493496/cebf1d6a-36eb-4f3d-97dd-7b5a255813d6)

![2024-04-13_02-46-51-790_brave](https://github.com/mrakowski0/readd-gmaps-links-chrome-extension/assets/26493496/df67c311-c319-408c-8ca8-c7504f2ff907)

**Comment by mrakowski0** [comment]
Thanks for this ticket and PR, I will go over these soon.
