### ISSUE TITLE
Button border style

### ISSUE THREAD

**Issue by lukasernsund** [mrakowski0/readd-gmaps-links-chrome-extension#5]
"Open in Maps" button border does not match button style in Chrome on MacOS, which does not have any border.

<img width="500" alt="image" src="https://github.com/mrakowski0/readd-gmaps-links-chrome-extension/assets/93626722/804f43af-abc4-46b1-bd47-40ccfde86b0a">

**Comment by mrakowski0** [comment]
Hi @lukasernsund thanks for creating the issue, I will try to fix it soon and release a new version.
Google has multiple UIs (tabs, buttons etc) that serve the same navigational purpose in google search page and I tried managing all of these cases but obviously its not being handled correctly 100% of the time👍

**Comment by mrakowski0** [comment]
Fixed in [1.0.10](https://github.com/mrakowski0/readd-gmaps-links-chrome-extension/releases/tag/1.0.10)
