### ISSUE TITLE
No chrome-based browser support

### ISSUE THREAD

**Issue by zamkorus** [mrakowski0/readd-gmaps-links-chrome-extension#6]
I can't make script run in opera, don't know why.
![image](https://github.com/mrakowski0/readd-gmaps-links-chrome-extension/assets/74738911/db9b843b-daee-4053-850d-d9a720ddbe21)

**Comment by mrakowski0** [comment]
Hi @xKRISTOFx, did you try to follow the Opera instructions from the extension description?

`You need to go to your extension settings in Opera, find this extension and tick the "Allow access to search page results" then refresh the page.`

Let me know if that works for you 👍

**Comment by mrakowski0** [comment]
Added this note to both extension text and this repo readme file.

**Comment by zamkorus** [comment]
Yup worked tsym. Tbh I was checking those settings before but somehow missed this one.

**Comment by mrakowski0** [comment]
Good to hear!
